### ISSUE TITLE
用户注册页面-密码是否要设置一定的复杂度

### ISSUE THREAD

**Issue by shao0099876** [shao0099876/AmyYoga#2]
用户注册页面，用户输入密码时是否要设置一定的复杂度等级，可以不提示密码安全等级？比如不能纯数字，不能纯字母的那种

**Comment by sherlklee** [comment]
我认为可以限制一下密码的长度，长度例如8~16位。不然为空，或者长度太短安全系数太低！可以考虑要求用户密码包含两类符号（数字和字母）。

**Comment by Littlle** [comment]
我觉得可以增加，太过于简单的密码容易被盗号。。。

**Comment by Vector-Change** [comment]
我觉得没必要增加工作难度！这个账号安全并不很重要，毕竟即使盗号了也不能付款＆上课
