### ISSUE TITLE
身份验证-客户注册账号用例中，对于输入的手机号是否需要增加检查机制？比如说长度不合理。

### ISSUE THREAD

**Issue by Littlle** [shao0099876/AmyYoga#4]

**Comment by shao0099876** [comment]
我本来有过这个想法，后来考虑到存在座机、短号、长途区号等情况，难以准确定义，可以将手机号输入框格式限定为全数字格式

**Comment by Littlle** [comment]
emmmm 还是觉得可能会有问题哎

**Comment by Vector-Change** [comment]
我觉得可以限制，这就是课设的时候zxd说的那个取值范围要固定，但是可以设置简单一点比如说必须11位数字之类的

**Comment by shao0099876** [comment]
如果固定的话就需要斟酌用户的手机号是否可能存在11位数之外的情况，例如座机号，短号之类的
