### ISSUE TITLE
登陆—退出登陆—登陆无法跳转到login

### ISSUE THREAD

**Issue by sherlklee** [shao0099876/AmyYoga#50]
**你的建议与一个问题相关联么？请描述你的问题**
在首页，点击登陆，进入登陆界面，成功登陆后，跳转到主页，点击登出，再次点击登陆按钮，页面停留在未登陆首页，无法跳转到登陆界面。

**描述你想要的解决方案**
forgetpassword函数和forgetpasswordlogin函数合并为一个函数，使用局部变量区分是否登陆，如果局部变量含义为未登录，则按forgetpasswordlogin函数逻辑。否则按照forgetpassword函数逻辑。局部变量的使用参考errormessage。

**Comment by shao0099876** [comment]
问题描述有差错，实际问题应当是访问forgetpassword并登陆后，一路退回，然后再访问forgetpassword就没有登录步骤，应当是没有消除掉session记录，以后也应当注意，在功能未完成之前对session做修改都是危险的
