### ISSUE TITLE
[Feature suggestions]用户注册时各项输入是否正确的判断顺序

### ISSUE THREAD

**Issue by Vector-Change** [shao0099876/AmyYoga#57]
**你的建议与一个问题相关联么？请描述你的问题**
用户注册时必填项是否为空的判断、两次密码不一致的判断、手机号格式的判断的先后顺序的改进。
当前顺序是先判断是否有空项，再判断最底部的生日格式，在判断两次输入的密码是否相同

**描述你想要的解决方案**
我认为应该填到哪里就判断到哪里，比如说我填写了两次密码，之后的选项没有填，此时我提交了，界面应该提示“两次密码不一致”而非在手机号那个空显示“请填写此字段”。
再比如我填写了手机号、两次密码和生日，但是我两次密码不一致而且生日格式不对，此时应该按照由上至下的顺序先提示“两次密码不一致”，更改后再提示“enter a valid date”，而现在的系统先提示的日期无效而非密码不一致

**描述你思考的替代方案（可选）**
更改逻辑判断顺序

**Comment by shao0099876** [comment]
这个逻辑判断顺序是由表单自动执行的，不过可以考虑重写表单，使用自定义验证机制

**Comment by shao0099876** [comment]
重写过后的表单验证依然是先确定表单字段是否为空，然后验证格式是否正确
