### ISSUE TITLE
未登录用户通过URL访问修改密码功能

### ISSUE THREAD

**Issue by Littlle** [shao0099876/AmyYoga#63]
**描述BUG**
清晰精确的描述BUG

**如何复现**
复现BUG的步骤:
1. 地址栏输入，http://127.0.0.1:8000/changepassword/

**预期的行为**
因为是未登录状态，界面应当跳转到登陆界面，而不是http://127.0.0.1:8000/forgetpassword/这个链接显示的界面。

**屏幕截图**
必要时附加屏幕截图

**运行环境**
 - 操作系统: win10
 - 浏览器 360

**更多内容**
添加关于该问题的更多信息

**Comment by shao0099876** [comment]
这个应当是算作一个feature，客户未登录状态访问修改密码功能可以看作是忘记密码尝试找回，被重定向到忘记密码页面，这一步不会对其他用户的信息安全性产生不良影响，如果在使用体验上有影响可以考虑修改

**Comment by Littlle** [comment]
都OK
