### ISSUE TITLE
未登录用户通过URL访问查看功能

### ISSUE THREAD

**Issue by Littlle** [shao0099876/AmyYoga#65]
**描述BUG**
清晰精确的描述BUG

**如何复现**
复现BUG的步骤:
1. 地址栏输入，http://127.0.0.1:8000/superusermessage/

**预期的行为**
应该是跳转到未登录前页面，而不是跳转到登陆界面。

**屏幕截图**
必要时附加屏幕截图

**运行环境**
 - 操作系统: win10
 - 浏览器 360

**更多内容**
添加关于该问题的更多信息

**Comment by shao0099876** [comment]
这个应当算是一个feature，访问该链接可以看作是管理员提前在收藏栏里收藏了该页面，直接尝试使用该功能，因此应当提供机会让他登陆。如果对使用体验有影响可以更改

**Comment by Littlle** [comment]
测试用例是这样，我绝得都可以。

**Comment by shao0099876** [comment]
（测试用例都是上辈子写的）

**Comment by YanzheL** [comment]
如果管理员cookie失效了，在未登录的情况下就能访问受限内容，这难道没问题嘛....
这还可能导致CSRF攻击吧....

**Comment by shao0099876** [comment]
> 如果管理员cookie失效了，在未登录的情况下就能访问受限内容，这难道没问题嘛....
> 这还可能导致CSRF攻击吧....

跳转到登录界面是指跳转到login界面进行身份验证登入
