### ISSUE TITLE
一段Q&A

### ISSUE THREAD

**Issue by shao0099876** [shao0099876/AmyYoga#7]
1. 在   课程-管理员增加课程  用例中：
       是否添加一个扩展场景：管理员取消增加（类比 课程-管理员修改课程 用例）
——应当有此场景
2. 在   身份验证-用户登出   用例中：
       注销账号和退出登录是不是两种的功能？？？但是情景中好像只描述了退出登陆的场景。
——是两种功能，但我认为注销账号功能使用概率趋近于0，我会做描述上的修改
3. 在   个人信息-客户完善个人信息  用例中：
       异常处理：
	* 1.任意内容框为空——提示内容为空，返回修改
      一定要求所有的内容都得填写？？？
——这里我会重新考虑必须填写的内容的范围
4. 在    购买记录-管理员确认订单   用例中：
        异常处理：是否也存在多次确认问题？？
——确认订单不存在多次确认问题，之前创建订单是+1;+1;+1……的过程，而确认订单相当于=1;=1;=1……的过程，多次确认发生时相当于重复将订单状态赋值为已确认，不需特别处理
5. 在   购买记录-管理员查看购买记录  用例中 ：
  差了一个异常处理（小细节  小细节）
——格式问题，会补充上
6. 在    身体评估报告-客户查看身体评估报告  用例中：
           扩展场景1：
	* 1.客户在搜索框中输入关键字内容，同时选择关键字类型
	* 2.系统动态显示模糊查询到的关键字信息
	是否需要模糊查询？？？根据什么查询？？
我觉得管理员需要模糊查询 （或者准确查询？），因为他可以根据用户名来查找某一位的所有的评估报告。
——客户的模糊查询在我设想中应当是查询段落对应的身体部位，例如模糊查询手臂、肩膀等部位，系统筛选出具有该身体部位对应段落的报告显示出来；管理员的模糊查询应当包含用户名或者客户名

**Comment by shao0099876** [comment]
这段Q来自佳哥233

**Comment by Littlle** [comment]
可以可以，就这样

**Comment by Vector-Change** [comment]
不好意思回复晚了，我还是觉得第二点里注销两种功能没必要。其余没意见
