### ISSUE TITLE
[Improvement]接口定义优化

### ISSUE THREAD

**Issue by YanzheL** [shao0099876/AmyYoga#75]
**描述**

AmyYoga/AmyYoga/AmyYoga/Interface/Interface.py

接口定义挺奇怪的

1. 你import了abc包，却没有使用abc包的任何组件？

2. 定义纯接口类，可以写的更规范一点。

两种方法

- 用abc包
```python
@six.add_metaclass(abc.ABCMeta)
class Interface(object):
    @abc.abstractmethod
    def method(self):
        pass
```
- 简单抛异常
```python
class Interface(object):
    def method(self):
        raise NotImplementedError
```
3. 你定义的所有接口方法都是实例方法，而不是类方法(这是对的)。因此根据传统，第一个参数名称应该是self吧，为什么你有的方法参数名称是cls？
   我知道cls和self只是个名称而已，不过不该用cls的地方还是别用吧，会引起混淆。
   你原意是想定义成类方法？我认为这里都使用实例方法即可，对应self参数

**Comment by shao0099876** [comment]
Interface已经弃用，当时cls是自动补全的，注意到这个问题后因为cls不是什么常用的具有特殊含义的组合，因此没特意去修正
