### ISSUE TITLE
[Feature suggestions]用户权限管理模块建议使用django提供的包

### ISSUE THREAD

**Issue by YanzheL** [shao0099876/AmyYoga#76]
**你的建议与一个问题相关联么？请描述你的问题**

用户登录模块可能有点太原始了，django理应提供更完善更成熟的用户权限管理模块实现。
而不需要开发者从头开始自定义接口，再手动完成用户鉴权管理。
你上django官网应该有权限管理相关文档。

既然选择使用框架，那么就最大限度的挖掘框架潜力吧

**描述你想要的解决方案**
使用官方提供的更完善的登录模块

**描述你思考的替代方案（可选）**
对你想要的功能提出任意的具体实施方案

**附加信息**

**Comment by shao0099876** [comment]
文档中确实有权限管理相关，但由于转换到权限管理在用户界面设计上的开销未知，因此不敢冒在框架不熟悉的情况下动刀子
