### ISSUE TITLE
我觉得可以增加：1.管理员排课（就是这个礼拜要上哪些课，在哪个地方上课，由哪个老师上课之类的，可能每个礼拜课不同，所以会需要排课）。2.管理员查看所有老师所被安排的课程情况（就是A老师这个礼拜只需要上三节课啊，或者五节课啊，将这个上课的次数作为发工资的依据之一）。3.管理员管理基础设施（比如增加教学工具？改善教学环境？之类的）。4.管理员发布活动（到了特定节假日，会有相应的优惠之类的）。5.用户查看活动？？ 只是突发奇想，大家看一下。

### ISSUE THREAD

**Issue by Littlle** [shao0099876/AmyYoga#8]

**Comment by shao0099876** [comment]
如果要增加教练这个角色，需要增加课表这样一个大功能模块，我觉得可以保留该想法，观察项目进度和工作量是否能够接受这个改动
基础设施这应当属于资产管理的功能，也需要斟酌工作量
优惠活动的话，但必须想好如何与课程的金额挂钩，因为购买课程时将会用到选择优惠活动，每种优惠活动可能有不同的优惠方式，例如满减和打折，是否有次数，不同课程是否都适用于不同的优惠活动

当然，选择权依然在你们，如果你们斟酌工作量后选择其中的一些或者某一些来做，这些功能需要你们来写正式用例，并在周天之前发布

**Comment by Vector-Change** [comment]
排课可以有
基础设施没必要啊我感觉，谁买个东西还得记录一下的？
发布活动必须有的，但具体如何打折之类的没必要特意弄，只需要让管理员写清楚就行了，比如说只要写3.8女王节全场八折 就行了，因为具体金额不需要计算
用户查看活动也应该有
